.TH KOS "1" "March 2022" "Kos" "General Commands Manual"


.SH NAME

kos - a simple SUID tool


.SH SYNOPSIS

.B kos
<\fIflag|?command\fR> [\fIargs...\fR]


.SH "FLAGS (IF \fIHAVE_ARG\fB ENABLED)"

.TP
\fB--version\fR
Print version and exit


.SH AUTHOR

Written by Ari Archer <\fIari.web.xyz@gmail.com\fR>


.SH "RETURN VALUE"

.TP
1
General error

.TP
2
Flag/argument parsing error

.TP
3
Failed to take user input

.TP
4
Failed/denied pipe

.TP
5
Terminal error

.TP
Anything else
The exit code of the command


.SH FILES

.TP
/etc/shadow
Secure user account information\&.

.TP
/etc/passwd
User account information\&.

.TP
/etc/group
The groups to which users belong under\&.


.SH "SEE ALSO"

.BR shadow (3)
.BR passwd (1)
.BR group (5)


.SH "REPORTING BUGS"

Report any bugs or feature requests to \fIhttps://ari-web.xyz/gh/kos\fR issues

