.TH KOS "1" "March 2022" "Kos" "General Commands Manual"


.SH NAME

kos \- a simple SUID tool


.SH SYNOPSIS

.B kos
<\fI\,COMMAND\/\fR> [\fI\,FLAGS\/\fR]


.SH AUTHOR

Written by Ari Archer <ari@mail.ari-web.xyz>


.SH "REPORTING BUGS"

Report any bugs or feature requests to https://ari-web.xyz/gh/kos issues

